version: '3.7'
services:
  thefarawaysummerevenings:
    build: './thefarawaysummerevenings'
    network_mode: host
    ports:
      - "5000:5000"
    container_name: thefarawaysummerevenings

  hypertextfacade:
    build: './hypertextfacade'
    network_mode: host
    ports:
      - "80:80"

  roomwithmontague:
    build: './roomwithmontague'
    network_mode: host
    ports:
      - "9000:9000"
    container_name: roomwithmontague