version: '3.7'
services:
  carrythatload:
    build: './carrythatload'
    ports:
      - "80:80"
    expose:
      - "80"
  thefarawaysummerevenings:
    build: './thefarawaysummerevenings'
    ports:
      - "5000:5000"
    expose:
      - "5000"
  roomwithmontague:
    build: './roomwithmontague'
    ports:
      - "9000:9000"
    expose:
      - "9000"