version: '3.7'
services:
  thefarawaysummerevenings:
    build: './thefarawaysummerevenings'
    restart: always
    expose:
      - 5000
    container_name: thefarawaysummerevenings

  roomwithmontague:
    build: './roomwithmontague'
    restart: on-failure
    expose:
      - 5000
    container_name: roomwithmontague

  wikidb:
    image: mongo:3
    expose:
      - '27017'
    command: '--smallfiles --bind_ip ::,0.0.0.0'
    environment:
      - 'MONGO_LOG_DIR=/dev/null'
    volumes:
      - ./data/mongo:/data/db

  wikijs:
    image: 'requarks/wiki:latest'
    links:
      - wikidb
    depends_on:
      - wikidb
    expose:
      - 80
    environment:
      WIKI_ADMIN_EMAIL: admin@example.com
    volumes:
      - ./wikijs/config.yml:/var/wiki/config.yml

  #Backendy things

  carrythatload: #nginx reverse proxy
    build: './carrythatload'
    restart: always
    ports:
      - "80:80"
    depends_on: 
      - roomwithmontague
      - thefarawaysummerevenings
    container_name: carrythatload
