version: '3.7'
services:
  thefarawaysummerevenings:
    build: './thefarawaysummerevenings'
    restart: always
    expose:
      - 5000
    container_name: thefarawaysummerevenings

  roomwithmontague:
    build: './roomwithmontague'
    restart: on-failure
    expose:
      - 5000
    container_name: roomwithmontague

  xwiki:
    image: "xwiki:postgres-tomcat"
    restart: always
    depends_on:
      - postdb
    expose:
      - 8080
    environment: 
      - DB_USER
      - DB_PASSWORD
      - DB_HOST=postdb
    volumes:
      - xwiki-data:/usr/local/xwiki
    container_name: xwiki

  #Backendy things

  carrythatload: #nginx reverse proxy
    build: './carrythatload'
    restart: always
    ports:
      - "80:80"
    depends_on: 
      - roomwithmontague
      - thefarawaysummerevenings
    container_name: carrythatload

  postdb: #primarily for xwiki
    image: "postgres:9.5"
    container_name: postdb
    restart: always
    volumes:
      - postgres-data:/var/lib/postgresql/data
    expose:
      - 5432
    environment:
      - POSTGRES_ROOT_PASSWORD
      - POSTGRES_USER
      - POSTGRES_DB=xwiki
      - POSTGRES_INITDB_ARGS="--encoding=UTF8"

volumes:
  postgres-data: {}
  xwiki-data: {}
    
