version: '3.7'
services:
  thefarawaysummerevenings:
    build: './thefarawaysummerevenings'
    restart: always
    expose:
      - 5000
    container_name: thefarawaysummerevenings

  roomwithmontague:
    build: './roomwithmontague'
    restart: on-failure
    expose:
      - 5000
    container_name: roomwithmontague

  xwiki:
    image: "xwiki:mysql-tomcat"
    container_name: xwiki
    depends_on:
      - db
    expose:
      - 8080
    environment:
      - DB_USER=xwiki
      - DB_PASSWORD=xwiki
      - DB_HOST=xwiki-mysql-db
    volumes:
      - xwiki-data:/usr/local/xwiki

  #Backendy things

  carrythatload: #nginx reverse proxy
    build: './carrythatload'
    restart: always
    ports:
      - "80:80"
    depends_on: 
      - roomwithmontague
      - thefarawaysummerevenings
    container_name: carrythatload
      
  db: #for xwiki
    image: "mysql:5.7"
    container_name: xwiki-mysql-db
    volumes:
      - ./xwiki.cnf:/etc/mysql/conf.d/xwiki.cnf
      - mysql-data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=xwiki
      - MYSQL_USER=xwiki
      - MYSQL_PASSWORD=xwiki
      - MYSQL_DATABASE=xwiki
    expose:
      - 3306
      - 33060

volumes:
  mysql-data: {}
  xwiki-data: {}