version: '3.7'
services:
  traefiking:
    image: traefik
    command: --api --docker
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  thefarawaysummerevenings:
    build: './thefarawaysummerevenings'
    ports:
      - "5000:5000"
    expose:
      - "5000"
  roomwithmontague:
    build: './roomwithmontague'
    ports:
      - "9000:9000"
    expose:
      - "9000"
  whoami: #for testing
    image: containous/whoami
    labels:
      - "traefik.frontend.rule=Host:whoami.docker.localhost"