version: '3.7'
services:
  thefarawaysummerevenings:
    build: './thefarawaysummerevenings'
    restart: always
    expose:
      - 5000
    container_name: thefarawaysummerevenings

  roomwithmontague:
    build: './roomwithmontague'
    restart: on-failure
    expose:
      - 5000
    container_name: roomwithmontague

  #Backendy things

  carrythatload: #nginx reverse proxy
    build: './carrythatload'
    restart: always
    ports:
      - "80:80"
    depends_on: 
      - roomwithmontague
      - thefarawaysummerevenings
    container_name: carrythatload

  #mongoDB for wikijs

  mongoose: 
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      - MONGO_INDB_ROOT_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD
      - MONGO_DATA_DIR=/mongoose/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - ./mongoose/db:/data/db
    container_name: mongoose