version: '3.7'
services:
  thefarawaysummerevenings:
    build: './thefarawaysummerevenings'
    restart: always
    expose:
      - 5000
    container_name: thefarawaysummerevenings

  roomwithmontague:
    build: './roomwithmontague'
    restart: on-failure
    container_name: roomwithmontague



  homofauxin:
    build: './homofauxin'
    restart: on-failure
    container_name: homofauxin

  xwiki:
    image: "xwiki:mysql-tomcat"
    container_name: xwiki
    depends_on:
      - db
    expose:
      - 8080
    environment:
      - DB_USER=xwiki
      - DB_PASSWORD=xwiki
      - DB_HOST=xwiki-mysql-db
    volumes:
      - xwiki-data:/usr/local/xwiki

  #Backendy things

  nginx: #nginx reverse proxy
    image: nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    container_name: nginx
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
      - ./carrythatload/nginx.conf:/etc/nginx/conf.d/nginx.conf
      - ./carrythatload/hypertext_facade:/usr/share/nginx/html


  # certbot:
  #   image: certbot/certbot
  #   restart: always
  #   container_name: certbot
  #   volumes:
  #     - ./data/certbot/conf:/etc/letsencrypt
  #     - ./data/certbot/www:/var/www/certbot
      
  db: #for xwiki
    image: "mysql:5.7"
    restart: always
    container_name: xwiki-mysql-db
    volumes:
      - ./xwiki.cnf:/etc/mysql/conf.d/xwiki.cnf
      - mysql-data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=xwiki
      - MYSQL_USER=xwiki
      - MYSQL_PASSWORD=xwiki
      - MYSQL_DATABASE=xwiki
    expose:
      - 3306
      - 33060

volumes:
  mysql-data: {}
  xwiki-data: {}