version: '3.7'
services:
  carrythatload:
    image: jwilder/nginx-proxy
    #ports:
    #  - "80:80"
    expose:
      - "80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    container_name: carrythatload
  
  thefarawaysummerevenings:
    build: './thefarawaysummerevenings'
    networks:
      - web
    #  - default
    #expose:
    #  - "5000"
    environment:
      - VIRTUAL_PORT=5000
      - VIRTUAL_HOST=thefaraway.titleduntitled.name
    container_name: thefarawaysummerevenings

  roomwithmontague:
    build: './roomwithmontague'
    networks:
      - web
    #  - default
    #expose:
    #  - "9000"
    environment:
      - VIRTUAL_PORT=9000
      - VIRTUAL_HOST=rooms.titleduntitled.name
    container_name: roomwithmontague

  whoami: #for testing
    image: containous/whoami
    labels:
      - "traefik.frontend.rule=Host:whoami.docker.localhost"

networks:
  reverse-proxy:
    external:
      name: reverse-proxy