debug = false

logLevel = "ERROR"
defaultEntryPoints = ["https", "http"]

[entryPoints]
    [entryPoints.http]
    address = ":80"
        [entrypoints.http.redirect]
        entryPoint = "https"
    [entryPoints.https]
    address = ":443"
    [entryPoints.https.tls]

[retry]

[docker]
enpoint = "unix:///var/run/docker.sock"
domain = "titleduntitled.name"
watch = true
exposedByDefault = false

[acme]
email = "notkrd@gmail.com"
storage = "acme.json"
entryPoint = "https"
onHostRule = true
[acme.httpChallenge]
entryPoint = "http"